application: mils-alumni
version: sandbox
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

handlers:
- url: /(robots\.txt)
  static_files: static/\1
  upload: static/(.*)

- url: /favicon\.ico
  static_files: static/image/favicon.png
  upload: static/image/favicon.png

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /image
  static_dir: static/image

- url: /_ah/queue/deferred
  script: main.py
  login: admin

- url: /.*
  script: main.py

builtins:
- remote_api: on
- appstats: on
- datastore_admin: on
- admin_redirect: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
